### ISSUE TITLE
abundant transcript vocabulary

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/tidybulk#89]
For a function that adds a column with .abundant label TRUE or FALSE do you think is better

- find_abundant
- identify_abundant
- label_abundant
- mark_abundant
- flag_abundant
- annotate_abundant
- ...

**Comment by mblue9** [comment]
hmm I don't have a strong preference but maybe identify_abundant? 
but will this be consistent with scale_abundance and test_differential_abundance which output the lowly_abundant column with TRUE for low abundant and FALSE if not abundant? as is your new function going to do the opposite - add TRUE if abundant & FALSE if not abundant? If so do you think that might be confusing and would adding in lowly be better e.g. identify_lowly_abundant?

**Comment by stemangiola** [comment]
The big picture:

I am making data filtering an external process (and warn if some processes usually need it but it has not been performed), so it is more clear what each function does, as they should do one thing only when possible (as we already discussed)

The introduction of a function that labels abundant genes:
I though in this case that a positive statement is better than a negation. In the same sense we keep abundant. So the new column produced will be `.abundant` TRUE/FALSE. (same think will happen with variable genes)

I know this breaks compatibility and should never be done, but the package is in a maturing phase, and sometimes some redesign is beneficial.

What do you think?

**Comment by mblue9** [comment]
Ok cool, makes sense. 

Here's my order of preference by what those function names suggest to me (feel free to disagree 😄 )
identify_abundant - is abundant true/false (that's the clearest to me for what it's going to do)
label_abundant - label seems like it's going to add a label that's more than just true/false?
mark_abundant - mark seems like it's going to add a mark that's more than just true/false?
flag_abundant - flag =bit jargony?
annotate_abundant - annotate sounds like it's going to add more info than just true/false?
find_abundant - "find is to encounter or discover by accident; to happen upon while identify is to establish the identity of someone or something" so find is not quite right?

One other thought, if changes like these break compatibility do you think there should/could be a tidybulk release made that remains stable for the bioc2020 workshop? the docker image will be stable but should we also pin a specific version of tidybulk so that the install from github  works in a reproducible way?

**Comment by stemangiola** [comment]
Cool I like identify_abundant too.

For the workshop, does not the docker image contain all the software with the right version? Another approach would be to point the dependency to the right github version, since R does not store all versions.

**Comment by mblue9** [comment]
>For the workshop, does not the docker image contain all the software with the right version? Another approach would be to point the dependency to the right github version, since R does not store all versions.

Yes the docker image should be fine, I was thinking of the alternative install from github method we put in the instructions. To point to right github version do you mean this? 
`install_github("stemangiola/tidybulk@v1.1.5")`
That is what I was thinking of i.e. changing the install instructions to specify the 1.1.5 version (tidybulk would need to add a 1.1.5 release tag I think?), assuming the breaking changes will be in >1.1.5.

**Comment by stemangiola** [comment]
That's exact. We should make clear that the right version is 1.1.5.

THERE COULD BE A TRAP THOUGH. If we update the README of Vignette, the docker image will be updated as well. For reproducibility purposes we should deactivate any automatic build of the docker image. Since the workshop has finished, that should never be changed again.

So while I don't think the vignette could change, we could put a note on the README. 

Coulple of notes:

- thats workshop will go as part of our workshop series on tidytranscriptomics, so people in the future will use that more I think
- the right way to update tidybulk should be in theory to create perameter deprecation and keep life the old framework for a while. So if the user uses the old parameter will be warned and the old framework will be used. In this case though, the framework is quite huge and duplicating all that code is not a joke, and I don't have the bandwidth to do all this now. So we have to do a small sacrifice in reproducibility. 

Let me know what you think about the docker business, you might have a better idea of me on that.

**Comment by mblue9** [comment]
I've made this PR now to the workshop to comment out the push to dockerhub so that workshop docker image is never overwritten https://github.com/stemangiola/bioc_2020_tidytranscriptomics/pull/41

Then I could update the README and website to use 1.1.5 

Could you make a release of tidybulk 1.1.5? 

so that if I add this it works `install_github("stemangiola/tidybulk@v1.1.5")`

**Comment by stemangiola** [comment]
Done https://github.com/stemangiola/tidybulk/releases/tag/v1.1.5
